DnD.JavaCsvToJson.DnDObject Class Reference
Public Member Functions
DnDObject (Property< String > pName, Property< String > pType, Property< String > pRarity, Property< Boolean > pLink, Property< String > pDescription)
List< String > mCSVHeaders ()
List< String > mToCSV ()
String mToJSON ()
List< String > mToBook ()
Static Public Member Functions
static DnDObject mFromURL (String vURL)
Package Attributes
Property< String > aName
Property< String > aType
Property< String > aRarity
Property< Boolean > aLink
Property< String > aDescription
Detailed Description
Constructor & Destructor Documentation
DnDObject()
DnD.JavaCsvToJson.DnDObject.DnDObject (Property< String > pName, Property< String > pType, Property< String > pRarity, Property< Boolean > pLink, Property< String > pDescription)
    {
        this.aName = pName;
        this.aType = pType;
        this.aRarity = pRarity;
        this.aLink = pLink;
        this.aDescription = pDescription;
    }
Referenced by mFromURL().
Member Function Documentation
mCSVHeaders()
List< String > DnD.JavaCsvToJson.DnDObject.mCSVHeaders ()
Implements DnD.JavaCsvToJson.IExportable.
    {
        List<String> vResult = new ArrayList<>();
        
        return vResult;
    }
mFromURL()
static DnDObject DnD.JavaCsvToJson.DnDObject.mFromURL (String vURL) [static]
    {
        DnDObject vResult = null;
        try
        {
            Document vDocument = Jsoup.connect(vURL.trim()).get();
            
            String vObjectName = vDocument.selectXpath("//div[@class='col1']/h1").text();
            String vTemp = vDocument.selectXpath("//div[@class='col1']//div[@class='type']").text();
            String vObjectType = null;
            boolean vLink = false;
            Pattern vPattern = Pattern.compile("(Anneau|Arme|Armure|Baguette|Bâton|Objet merveilleux|Parchemin|Potion|Sceptre)");
            Matcher vMatcher = vPattern.matcher(vTemp);
            if(vMatcher.find())
            {
                vObjectType = vMatcher.group();
            }
            String vRarity = null;
            vPattern = Pattern.compile("(commun|variable|peu commun|peu commun \\(\\+1\\) rare \\(\\+2\\) ou très rare \\(\\+3\\)|rareté selon le type de statuette|rare|rare \\(\\+1\\) très rare \\(\\+2\\) ou légendaire \\(\\+3\\)|très rare|très rare ou légendaire|légendaire|artéfact)");
            vMatcher = vPattern.matcher(vTemp);
            if (vMatcher.find())
            {
                vRarity = vMatcher.group();
            }
            if(vTemp.contains("nécessite un lien"))
            {
                vLink = true;
            }
            
            String vDescription = vDocument.selectXpath("//div[@class='col1']//div[@class='resume']").text();
            if(!vDescription.isEmpty())
            {
                vDescription += "\n";
            }
            vDescription += vDocument.selectXpath("//div[@class='col1']//div[@class='description']").text();
            
            vResult = new DnDObject
            (
                new Property<String>(EObjectHeader.Name, vObjectName),
                new Property<String>(EObjectHeader.Type, vObjectType),
                new Property<String>(EObjectHeader.Rarity, vRarity),
                new Property<Boolean>(EObjectHeader.Link, vLink),
                new Property<String>(EObjectHeader.Description, vDescription)
            );
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
        return vResult;
    }
References DnD.JavaCsvToJson.EObjectHeader.Description, DnDObject(), DnD.JavaCsvToJson.EObjectHeader.Link, DnD.JavaCsvToJson.EObjectHeader.Name, DnD.JavaCsvToJson.EObjectHeader.Rarity, and DnD.JavaCsvToJson.EObjectHeader.Type.
Referenced by DnD.JavaCsvToJson.JavaCsvToJson.start().
mToBook()
List< String > DnD.JavaCsvToJson.DnDObject.mToBook ()
Implements DnD.JavaCsvToJson.IExportable.
    {
        List<String> vResult = new ArrayList<>();
        vResult.addAll(this.aName.mToBook());
        vResult.addAll(this.aType.mToBook());
        vResult.addAll(this.aRarity.mToBook());
        vResult.addAll(this.aLink.mToBook());
        vResult.addAll(this.aDescription.mToBook());
        return vResult;
    }
References DnD.JavaCsvToJson.Property< T >.mToBook().
mToCSV()
List< String > DnD.JavaCsvToJson.DnDObject.mToCSV ()
Implements DnD.JavaCsvToJson.IExportable.
    {
        List<String> vResult = new ArrayList<>();
        
        return vResult;
    }
mToJSON()
String DnD.JavaCsvToJson.DnDObject.mToJSON ()
Implements DnD.JavaCsvToJson.IExportable.
    {
        return "";
    }
Member Data Documentation
aDescription
Property<String> DnD.JavaCsvToJson.DnDObject.aDescription [package]
aLink
Property<Boolean> DnD.JavaCsvToJson.DnDObject.aLink [package]
aName
Property<String> DnD.JavaCsvToJson.DnDObject.aName [package]
aRarity
Property<String> DnD.JavaCsvToJson.DnDObject.aRarity [package]
aType
Property<String> DnD.JavaCsvToJson.DnDObject.aType [package]
The documentation for this class was generated from the following file:
src/main/java/DnD/JavaCsvToJson/DnDObject.java