DnD.JavaCsvToJson.AvatarFrame Class Reference
Public Member Functions
Property< String > mAvatar ()
Property< String > mToken ()
String mToJSON ()
List< String > mCSVHeaders ()
List< String > mToCSV ()
List< String > mToBook ()
Static Public Member Functions
static AvatarFrame mFromJson (JSONObject pJson)
Package Functions
AvatarFrame (Property< String > pAvatar, Property< String > pToken)
Private Attributes
Property< String > aAvatar
Property< String > aToken
Detailed Description
Constructor & Destructor Documentation
AvatarFrame()
DnD.JavaCsvToJson.AvatarFrame.AvatarFrame (Property< String > pAvatar, Property< String > pToken) [package]
    {
        this.aAvatar = pAvatar;
        this.aToken = pToken;
    }
Referenced by mFromJson().
Member Function Documentation
mAvatar()
Property< String > DnD.JavaCsvToJson.AvatarFrame.mAvatar ()
    {
        return this.aAvatar;
    }
mCSVHeaders()
List< String > DnD.JavaCsvToJson.AvatarFrame.mCSVHeaders ()
Implements DnD.JavaCsvToJson.IExportable.
    {
        List<String> vResult = new ArrayList<>();
        
        vResult.add(this.aAvatar.mName());
        vResult.add(this.aToken.mName());
        
        return vResult;
    }
References DnD.JavaCsvToJson.Property< T >.mName().
mFromJson()
static AvatarFrame DnD.JavaCsvToJson.AvatarFrame.mFromJson (JSONObject pJson) [static]
    {
        AvatarFrame vFrame = null;
        String vAvatar = (String) pJson.getOrDefault(EMonsterHeader.Avatar.mJsonName(), null);
        if(vAvatar != null && vAvatar.equalsIgnoreCase("null"))
        {
            vAvatar = null;
        }
        String vToken = (String) pJson.getOrDefault(EMonsterHeader.Token.mJsonName(), null);
        if(vToken != null && vToken.equalsIgnoreCase("null"))
        {
            vToken = null;
        }
        vFrame = new AvatarFrame
        (
            new Property<String>(EMonsterHeader.Avatar, vAvatar),
            new Property<String>(EMonsterHeader.Token, vToken)
        );
        return vFrame;
    }
References DnD.JavaCsvToJson.EMonsterHeader.Avatar, AvatarFrame(), and DnD.JavaCsvToJson.EMonsterHeader.Token.
Referenced by DnD.JavaCsvToJson.MonsterAvatar.mFromJson().
mToBook()
List< String > DnD.JavaCsvToJson.AvatarFrame.mToBook ()
Implements DnD.JavaCsvToJson.IExportable.
    {
        List<String> vResult = new ArrayList<>();
        
        vResult.addAll(this.aAvatar.mToBook());
        vResult.addAll(this.aToken.mToBook());
        
        return vResult;
    }
References DnD.JavaCsvToJson.Property< T >.mToBook().
mToCSV()
List< String > DnD.JavaCsvToJson.AvatarFrame.mToCSV ()
Implements DnD.JavaCsvToJson.IExportable.
    {
        List<String> vResult = new ArrayList<>();
        
        vResult.add(this.aAvatar.mToCSV());
        vResult.add(this.aToken.mToCSV());
        
        return vResult;
    }
References DnD.JavaCsvToJson.Property< T >.mToCSV().
mToJSON()
String DnD.JavaCsvToJson.AvatarFrame.mToJSON ()
Implements DnD.JavaCsvToJson.IExportable.
    {
        return "";
    }
mToken()
Property< String > DnD.JavaCsvToJson.AvatarFrame.mToken ()
    {
        return this.aToken;
    }
Member Data Documentation
aAvatar
Property<String> DnD.JavaCsvToJson.AvatarFrame.aAvatar [private]
aToken
Property<String> DnD.JavaCsvToJson.AvatarFrame.aToken [private]
The documentation for this class was generated from the following file:
src/main/java/DnD/JavaCsvToJson/AvatarFrame.java