DnD.JavaCsvToJson.MonsterAvatar Class Reference
Public Member Functions
Property< String > mAvatar ()
Property< String > mToken ()
Property< AvatarFrame > mFrame ()
String mToJSON ()
List< String > mCSVHeaders ()
List< String > mToCSV ()
List< String > mToBook ()
Static Public Member Functions
static MonsterAvatar mFromJson (JSONObject vJson)
Package Functions
MonsterAvatar (Property< String > pAvatar, Property< String > pToken, Property< AvatarFrame > pFrame)
Private Attributes
Property< String > aAvatar
Property< String > aToken
Property< AvatarFrame > aFrame
Detailed Description
Constructor & Destructor Documentation
MonsterAvatar()
DnD.JavaCsvToJson.MonsterAvatar.MonsterAvatar (Property< String > pAvatar, Property< String > pToken, Property< AvatarFrame > pFrame) [package]
    {
        this.aAvatar = pAvatar;
        this.aToken = pToken;
        this.aFrame = pFrame;
    }
Referenced by mFromJson().
Member Function Documentation
mAvatar()
Property< String > DnD.JavaCsvToJson.MonsterAvatar.mAvatar ()
    {
        return this.aAvatar ;
    }
mCSVHeaders()
List< String > DnD.JavaCsvToJson.MonsterAvatar.mCSVHeaders ()
Implements DnD.JavaCsvToJson.IExportable.
    {
        List<String> vResult = new ArrayList<>();
        
        vResult.add(this.aAvatar.mName());
        vResult.add(this.aToken.mName());
        vResult.add(this.aFrame.mName());
        vResult.addAll(this.aFrame.mValue().mCSVHeaders());
        return vResult;
    }
References DnD.JavaCsvToJson.Property< T >.mName(), and DnD.JavaCsvToJson.Property< T >.mValue().
mFrame()
Property< AvatarFrame > DnD.JavaCsvToJson.MonsterAvatar.mFrame ()
    {
        return this.aFrame;
    }
mFromJson()
static MonsterAvatar DnD.JavaCsvToJson.MonsterAvatar.mFromJson (JSONObject vJson) [static]
    {
        MonsterAvatar vResult = null;
        String vAvatar = (String) vJson.getOrDefault(EMonsterHeader.Avatar.mJsonName(), null);
        if(vAvatar != null && vAvatar.equalsIgnoreCase("null"))
        {
            vAvatar = null;
        }
        String vToken = (String) vJson.getOrDefault(EMonsterHeader.Token.mJsonName(), null);
        if(vToken != null && vToken.equalsIgnoreCase("null"))
        {
            vToken = null;
        }
        JSONObject vJsonFrame = (JSONObject) vJson.getOrDefault(EMonsterHeader.Frame.mJsonName(), null);
        AvatarFrame vAvatarFrame;
        if(vJsonFrame != null)
        {
            vAvatarFrame = AvatarFrame.mFromJson(vJsonFrame);
        }
        else
        {
            vAvatarFrame = new AvatarFrame
            (
                new Property<String>(EMonsterHeader.Avatar, null),
                new Property<String>(EMonsterHeader.Token, null)
            );
        }
        vResult = new MonsterAvatar
        (
            new Property<String>(EMonsterHeader.Avatar, vAvatar),
            new Property<String>(EMonsterHeader.Token, vToken),
            new Property<AvatarFrame>(EMonsterHeader.Frame, vAvatarFrame)
        );
        return vResult;
    }
References DnD.JavaCsvToJson.EMonsterHeader.Avatar, DnD.JavaCsvToJson.EMonsterHeader.Frame, DnD.JavaCsvToJson.AvatarFrame.mFromJson(), MonsterAvatar(), and DnD.JavaCsvToJson.EMonsterHeader.Token.
Referenced by DnD.JavaCsvToJson.Monster.mFromJson().
mToBook()
List< String > DnD.JavaCsvToJson.MonsterAvatar.mToBook ()
Implements DnD.JavaCsvToJson.IExportable.
    {
        List<String> vResult = new ArrayList<>();
        vResult.add(this.aAvatar.mNameJSON());
        vResult.add(this.aAvatar.mToCSV());
        vResult.add(this.aToken.mNameJSON());
        vResult.add(this.aToken.mToCSV());
        vResult.add("");
        vResult.add(this.aFrame.mNameJSON());
        vResult.addAll(this.aFrame.mValue().mToBook());
        return vResult;
    }
References DnD.JavaCsvToJson.Property< T >.mNameJSON(), DnD.JavaCsvToJson.Property< T >.mToCSV(), and DnD.JavaCsvToJson.Property< T >.mValue().
mToCSV()
List< String > DnD.JavaCsvToJson.MonsterAvatar.mToCSV ()
Implements DnD.JavaCsvToJson.IExportable.
    {
        List<String> vResult = new ArrayList<>();
        vResult.add(this.aAvatar.mToCSV());
        vResult.add(this.aToken.mToCSV());
        vResult.add("");
        vResult.addAll(this.aFrame.mValue().mToCSV());
        return vResult;
    }
References DnD.JavaCsvToJson.Property< T >.mToCSV(), and DnD.JavaCsvToJson.Property< T >.mValue().
mToJSON()
String DnD.JavaCsvToJson.MonsterAvatar.mToJSON ()
Implements DnD.JavaCsvToJson.IExportable.
    {
        return "";
    }
mToken()
Property< String > DnD.JavaCsvToJson.MonsterAvatar.mToken ()
    {
        return this.aToken;
    }
Member Data Documentation
aAvatar
Property<String> DnD.JavaCsvToJson.MonsterAvatar.aAvatar [private]
aFrame
Property<AvatarFrame> DnD.JavaCsvToJson.MonsterAvatar.aFrame [private]
aToken
Property<String> DnD.JavaCsvToJson.MonsterAvatar.aToken [private]
The documentation for this class was generated from the following file:
src/main/java/DnD/JavaCsvToJson/MonsterAvatar.java