DnD.JavaCsvToJson.SpellAttack Class Reference
Public Member Functions
SpellAttack (Property< String > pSpellTime, Property< String > pSpellRange, Property< String > pSpellDuration, Property< Boolean > pRitualCast, Property< Boolean > pConcentration, Property< Boolean > pSpellComponentV, Property< Boolean > pSpellComponentS, Property< Boolean > pSpellComponentM, Property< String > pSpellComponentDescription, Property< Boolean > pMaterialCost, Property< ESpellAttackType > pSaveThrow, Property< String > pSpellDamage, Property< String > pSpellDescription, Property< Boolean > pSpellLegendary)
Property< String > mSpellTime ()
Property< String > mSpellRange ()
Property< String > mSpellDuration ()
Property< Boolean > mRitualCast ()
Property< Boolean > mConcentration ()
Property< Boolean > mSpellComponentV ()
Property< Boolean > mSpellComponentS ()
Property< Boolean > mSpellComponentM ()
Property< String > mSpellComponentDescription ()
Property< Boolean > mMaterialCost ()
Property< ESpellAttackType > mSaveThrow ()
Property< String > mSpeelDamage ()
Property< Boolean > mSpellLegendary ()
Property< String > mSpellDescription ()
String mToJSON ()
List< String > mCSVHeaders ()
List< String > mToCSV ()
List< String > mToBook ()
Private Attributes
Property< String > aSpellTime
Property< String > aSpellRange
Property< String > aSpellDuration
Property< Boolean > aRitualCast
Property< Boolean > aConcentration
Property< Boolean > aSpellComponentV
Property< Boolean > aSpellComponentS
Property< Boolean > aSpellComponentM
Property< String > aSpellComponentDescription
Property< Boolean > aMaterialCost
Property< ESpellAttackType > aSaveThrow
Property< String > aSpellDamage
Property< String > aSpellDescription
Property< Boolean > aSpellLegendary
Detailed Description
Constructor & Destructor Documentation
SpellAttack()
DnD.JavaCsvToJson.SpellAttack.SpellAttack (Property< String > pSpellTime, Property< String > pSpellRange, Property< String > pSpellDuration, Property< Boolean > pRitualCast, Property< Boolean > pConcentration, Property< Boolean > pSpellComponentV, Property< Boolean > pSpellComponentS, Property< Boolean > pSpellComponentM, Property< String > pSpellComponentDescription, Property< Boolean > pMaterialCost, Property< ESpellAttackType > pSaveThrow, Property< String > pSpellDamage, Property< String > pSpellDescription, Property< Boolean > pSpellLegendary)
    {
        this.aSpellTime = pSpellTime;
        this.aSpellRange = pSpellRange;
        this.aSpellDuration = pSpellDuration;
        this.aRitualCast = pRitualCast;
        this.aConcentration = pConcentration;
        this.aSpellComponentV = pSpellComponentV;
        this.aSpellComponentS = pSpellComponentS;
        this.aSpellComponentM = pSpellComponentM;
        this.aSpellComponentDescription = pSpellComponentDescription;
        this.aMaterialCost = pMaterialCost;
        //this.aSpellAttackType = null;
        this.aSaveThrow = pSaveThrow;
        this.aSpellDamage = pSpellDamage;
        //this.aSpellDamageType = null;
        this.aSpellDescription = pSpellDescription;
        this.aSpellLegendary = pSpellLegendary;
    }
Member Function Documentation
mConcentration()
Property< Boolean > DnD.JavaCsvToJson.SpellAttack.mConcentration ()
    {
        return this.aConcentration;
    }
mCSVHeaders()
List< String > DnD.JavaCsvToJson.SpellAttack.mCSVHeaders ()
Implements DnD.JavaCsvToJson.IExportable.
    {
        List<String> vResult = new ArrayList<>();
        vResult.add(this.aSpellTime.mName());
        vResult.add(this.aSpellRange.mName());
        vResult.add(this.aSpellDuration.mName());
        vResult.add(this.aRitualCast.mName());
        vResult.add(this.aConcentration.mName());
        vResult.add(this.aSpellComponentV.mName());
        vResult.add(this.aSpellComponentS.mName());
        vResult.add(this.aSpellComponentM.mName());
        vResult.add(this.aSpellComponentDescription.mName());
        vResult.add(this.aSaveThrow.mName());
        vResult.add(this.aSpellDamage.mName());
        vResult.add(this.aSpellDescription.mName());
        
        return vResult;
    }
References DnD.JavaCsvToJson.Property< T >.mName().
mMaterialCost()
Property< Boolean > DnD.JavaCsvToJson.SpellAttack.mMaterialCost ()
    {
        return this.aMaterialCost;
    }
mRitualCast()
Property< Boolean > DnD.JavaCsvToJson.SpellAttack.mRitualCast ()
    {
        return this.aRitualCast;
    }
mSaveThrow()
Property< ESpellAttackType > DnD.JavaCsvToJson.SpellAttack.mSaveThrow ()
    {
        return this.aSaveThrow;
    }
mSpeelDamage()
Property< String > DnD.JavaCsvToJson.SpellAttack.mSpeelDamage ()
    {
        return this.aSpellDamage;
    }
mSpellComponentDescription()
Property< String > DnD.JavaCsvToJson.SpellAttack.mSpellComponentDescription ()
    {
        return this.aSpellComponentDescription;
    }
mSpellComponentM()
Property< Boolean > DnD.JavaCsvToJson.SpellAttack.mSpellComponentM ()
    {
        return this.aSpellComponentM;
    }
mSpellComponentS()
Property< Boolean > DnD.JavaCsvToJson.SpellAttack.mSpellComponentS ()
    {
        return this.aSpellComponentS;
    }
mSpellComponentV()
Property< Boolean > DnD.JavaCsvToJson.SpellAttack.mSpellComponentV ()
    {
        return this.aSpellComponentV;
    }
mSpellDescription()
Property< String > DnD.JavaCsvToJson.SpellAttack.mSpellDescription ()
    {
        return this.aSpellDescription;
    }
mSpellDuration()
Property< String > DnD.JavaCsvToJson.SpellAttack.mSpellDuration ()
    {
        return this.aSpellDuration;
    }
mSpellLegendary()
Property< Boolean > DnD.JavaCsvToJson.SpellAttack.mSpellLegendary ()
    {
        return this.aSpellLegendary;
    }
mSpellRange()
Property< String > DnD.JavaCsvToJson.SpellAttack.mSpellRange ()
    {
        return this.aSpellRange;
    }
mSpellTime()
Property< String > DnD.JavaCsvToJson.SpellAttack.mSpellTime ()
    {
        return this.aSpellTime;
    }
mToBook()
List< String > DnD.JavaCsvToJson.SpellAttack.mToBook ()
Implements DnD.JavaCsvToJson.IExportable.
    {
        List<String> vResult = new ArrayList<>();
        
        vResult.addAll(this.aSpellTime.mToBook());
        vResult.addAll(this.aSpellRange.mToBook());
        vResult.addAll(this.aSpellDuration.mToBook());
        vResult.addAll(this.aRitualCast.mToBook());
        vResult.addAll(this.aConcentration.mToBook());
        vResult.addAll(this.aSpellComponentV.mToBook());
        vResult.addAll(this.aSpellComponentS.mToBook());
        vResult.addAll(this.aSpellComponentM.mToBook());
        vResult.addAll(this.aSpellComponentDescription.mToBook());
        vResult.addAll(this.aSaveThrow.mToBook());
        vResult.addAll(this.aSpellDamage.mToBook());
        vResult.addAll(this.aSpellDescription.mToBook());
        vResult.addAll(this.aSpellLegendary.mToBook());
        return vResult;
    }
References DnD.JavaCsvToJson.Property< T >.mToBook().
mToCSV()
List< String > DnD.JavaCsvToJson.SpellAttack.mToCSV ()
Implements DnD.JavaCsvToJson.IExportable.
    {
        List<String> vResult = new ArrayList<>();
        vResult.add(this.aSpellTime.mToCSV());
        vResult.add(this.aSpellRange.mToCSV());
        vResult.add(this.aSpellDuration.mToCSV());
        vResult.add(this.aRitualCast.mToCSV());
        vResult.add(this.aConcentration.mToCSV());
        vResult.add(this.aSpellComponentV.mToCSV());
        vResult.add(this.aSpellComponentS.mToCSV());
        vResult.add(this.aSpellComponentM.mToCSV());
        vResult.add(this.aSpellComponentDescription.mToCSV());
        vResult.add(this.aSaveThrow.mToCSV());
        vResult.add(this.aSpellDamage.mToCSV());
        vResult.add(this.aSpellDescription.mToCSV());
        return vResult;
    }
References DnD.JavaCsvToJson.Property< T >.mToCSV().
mToJSON()
String DnD.JavaCsvToJson.SpellAttack.mToJSON ()
Implements DnD.JavaCsvToJson.IExportable.
    {
        return this.aSpellTime.mToJSON() +
                ",\n " + this.aSpellRange.mToJSON() +
                ",\n " + this.aSpellDuration.mToJSON() +
                ",\n " + this.aRitualCast.mToJSON() +
                ",\n " + this.aConcentration.mToJSON() +
                ",\n " + this.aSpellComponentV.mToJSON() +
                ",\n " + this.aSpellComponentS.mToJSON() +
                ",\n " + this.aSpellComponentM.mToJSON() +
                ",\n " + this.aSpellComponentDescription.mToJSON() +
                ",\n " + this.aMaterialCost.mToJSON() +
                ",\n " + this.aSaveThrow.mToJSON() +
                ",\n " + this.aSpellDamage.mToJSON() +
                ",\n " + this.aSpellDescription.mToJSON();
    }
References DnD.JavaCsvToJson.Property< T >.mToJSON().
Member Data Documentation
aConcentration
Property<Boolean> DnD.JavaCsvToJson.SpellAttack.aConcentration [private]
aMaterialCost
Property<Boolean> DnD.JavaCsvToJson.SpellAttack.aMaterialCost [private]
aRitualCast
Property<Boolean> DnD.JavaCsvToJson.SpellAttack.aRitualCast [private]
aSaveThrow
Property<ESpellAttackType> DnD.JavaCsvToJson.SpellAttack.aSaveThrow [private]
aSpellComponentDescription
Property<String> DnD.JavaCsvToJson.SpellAttack.aSpellComponentDescription [private]
aSpellComponentM
Property<Boolean> DnD.JavaCsvToJson.SpellAttack.aSpellComponentM [private]
aSpellComponentS
Property<Boolean> DnD.JavaCsvToJson.SpellAttack.aSpellComponentS [private]
aSpellComponentV
Property<Boolean> DnD.JavaCsvToJson.SpellAttack.aSpellComponentV [private]
aSpellDamage
Property<String> DnD.JavaCsvToJson.SpellAttack.aSpellDamage [private]
aSpellDescription
Property<String> DnD.JavaCsvToJson.SpellAttack.aSpellDescription [private]
aSpellDuration
Property<String> DnD.JavaCsvToJson.SpellAttack.aSpellDuration [private]
aSpellLegendary
Property<Boolean> DnD.JavaCsvToJson.SpellAttack.aSpellLegendary [private]
aSpellRange
Property<String> DnD.JavaCsvToJson.SpellAttack.aSpellRange [private]
aSpellTime
Property<String> DnD.JavaCsvToJson.SpellAttack.aSpellTime [private]
The documentation for this class was generated from the following file:
src/main/java/DnD/JavaCsvToJson/SpellAttack.java