DnD.JavaCsvToJson.Property< T > Class Template Reference
Public Member Functions
Property (Enum<? extends IHeader > pHeader, T pValue)
String mName ()
String mNameJSON ()
boolean mQuoted ()
T mValue ()
void mValue (T pValue)
String mToJSON ()
String mToCSV ()
List< String > mToBook ()
Private Attributes
String aName
String aNameJSON
boolean aQuoted
T aValue
Detailed Description
Constructor & Destructor Documentation
Property()
DnD.JavaCsvToJson.Property< T >.Property (Enum<? extends IHeader > pHeader, T pValue)
    {
        this.aName = ((IHeader)pHeader).mName();
        this.aNameJSON = ((IHeader)pHeader).mJsonName();
        this.aQuoted = ((IHeader)pHeader).mQuoted();
        this.aValue = pValue;
    }
References mName(), and mQuoted().
Member Function Documentation
mName()
String DnD.JavaCsvToJson.Property< T >.mName ()
    {
        return this.aName;
    }
Referenced by DnD.JavaCsvToJson.AvatarFrame.mCSVHeaders(), DnD.JavaCsvToJson.Monster.mCSVHeaders(), DnD.JavaCsvToJson.MonsterAvatar.mCSVHeaders(), DnD.JavaCsvToJson.Spell.mCSVHeaders(), DnD.JavaCsvToJson.SpellAttack.mCSVHeaders(), and Property().
mNameJSON()
String DnD.JavaCsvToJson.Property< T >.mNameJSON ()
    {
        return this.aNameJSON;
    }
Referenced by DnD.JavaCsvToJson.MonsterAvatar.mToBook().
mQuoted()
boolean DnD.JavaCsvToJson.Property< T >.mQuoted ()
    {
        return this.aQuoted;
    }
Referenced by Property().
mToBook()
List< String > DnD.JavaCsvToJson.Property< T >.mToBook ()
    {
        List<String> vResult = new ArrayList<>();
        if(this.aValue != null)
        {
            vResult.add(this.aNameJSON);
            if (!(this.aValue instanceof List<?>))
            {
                vResult.add(this.aValue.toString());
            }
        }
        return vResult;
    }
Referenced by DnD.JavaCsvToJson.AvatarFrame.mToBook(), DnD.JavaCsvToJson.Monster.mToBook(), DnD.JavaCsvToJson.MonsterAction.mToBook(), and DnD.JavaCsvToJson.SpellAttack.mToBook().
mToCSV()
String DnD.JavaCsvToJson.Property< T >.mToCSV ()
    {
        String vResult = null;
        if(this.aValue != null)
        {
            vResult = this.aValue.toString();
        }
        return vResult;
    }
Referenced by DnD.JavaCsvToJson.MonsterAvatar.mToBook(), DnD.JavaCsvToJson.AvatarFrame.mToCSV(), DnD.JavaCsvToJson.Monster.mToCSV(), DnD.JavaCsvToJson.MonsterAvatar.mToCSV(), DnD.JavaCsvToJson.Spell.mToCSV(), and DnD.JavaCsvToJson.SpellAttack.mToCSV().
mToJSON()
String DnD.JavaCsvToJson.Property< T >.mToJSON ()
    {
        String vResult = "";
        if(!this.aQuoted)
        {
            vResult += "\"\"" + this.aNameJSON + "\"\": " + this.aValue.toString();
        }
        else
        {
            vResult += "\"\"" + this.aNameJSON + "\"\": \"\"" + this.aValue.toString() + "\"\"";
        }
        return vResult;
    }
Referenced by DnD.JavaCsvToJson.Spell.mToJSON(), and DnD.JavaCsvToJson.SpellAttack.mToJSON().
mValue() [1/2]
T DnD.JavaCsvToJson.Property< T >.mValue ()
    {
        return this.aValue;
    }
Referenced by DnD.JavaCsvToJson.Monster.mCSVHeaders(), DnD.JavaCsvToJson.MonsterAvatar.mCSVHeaders(), DnD.JavaCsvToJson.Monster.mToBook(), DnD.JavaCsvToJson.MonsterAction.mToBook(), DnD.JavaCsvToJson.MonsterAvatar.mToBook(), DnD.JavaCsvToJson.MonsterProperty.mToBook(), DnD.JavaCsvToJson.Monster.mToCSV(), DnD.JavaCsvToJson.MonsterAvatar.mToCSV(), and DnD.JavaCsvToJson.MonsterProperty.mToCSV().
mValue() [2/2]
void DnD.JavaCsvToJson.Property< T >.mValue (T pValue)
    {
        this.aValue = pValue;
    }
Member Data Documentation
aName
String DnD.JavaCsvToJson.Property< T >.aName [private]
aNameJSON
String DnD.JavaCsvToJson.Property< T >.aNameJSON [private]
aQuoted
boolean DnD.JavaCsvToJson.Property< T >.aQuoted [private]
aValue
T DnD.JavaCsvToJson.Property< T >.aValue [private]
The documentation for this class was generated from the following file:
src/main/java/DnD/JavaCsvToJson/Property.java