var dir_ce8aa0809cd6cb8d91f3956e287aa834 =
[
    [ "App.java", "dc/d0d/App_8java.html", "dc/d0d/App_8java" ],
    [ "AvatarFrame.java", "df/dd6/AvatarFrame_8java.html", "df/dd6/AvatarFrame_8java" ],
    [ "Digest.java", "d7/d39/Digest_8java.html", "d7/d39/Digest_8java" ],
    [ "DnDObject.java", "d3/de5/DnDObject_8java.html", "d3/de5/DnDObject_8java" ],
    [ "EAlignment.java", "df/dfb/EAlignment_8java.html", "df/dfb/EAlignment_8java" ],
    [ "EApplicationStatus.java", "d3/d98/EApplicationStatus_8java.html", "d3/d98/EApplicationStatus_8java" ],
    [ "EDices.java", "d0/ddf/EDices_8java.html", "d0/ddf/EDices_8java" ],
    [ "EMonsterHeader.java", "dd/d1d/EMonsterHeader_8java.html", "dd/d1d/EMonsterHeader_8java" ],
    [ "EObjectHeader.java", "d9/dd8/EObjectHeader_8java.html", "d9/dd8/EObjectHeader_8java" ],
    [ "ESize.java", "df/dbe/ESize_8java.html", "df/dbe/ESize_8java" ],
    [ "ESpellAttackType.java", "d5/d04/ESpellAttackType_8java.html", "d5/d04/ESpellAttackType_8java" ],
    [ "ESpellDamageType.java", "d9/dfa/ESpellDamageType_8java.html", "d9/dfa/ESpellDamageType_8java" ],
    [ "ESpellHeader.java", "d9/dc2/ESpellHeader_8java.html", "d9/dc2/ESpellHeader_8java" ],
    [ "ESpellLevel.java", "d8/de0/ESpellLevel_8java.html", "d8/de0/ESpellLevel_8java" ],
    [ "ESpellSchool.java", "d3/d51/ESpellSchool_8java.html", "d3/d51/ESpellSchool_8java" ],
    [ "IExportable.java", "d2/d92/IExportable_8java.html", "d2/d92/IExportable_8java" ],
    [ "IHeader.java", "db/df0/IHeader_8java.html", "db/df0/IHeader_8java" ],
    [ "JavaCsvToJson.java", "da/d45/JavaCsvToJson_8java.html", "da/d45/JavaCsvToJson_8java" ],
    [ "Monster.java", "da/d64/Monster_8java.html", "da/d64/Monster_8java" ],
    [ "MonsterAction.java", "d4/ddd/MonsterAction_8java.html", "d4/ddd/MonsterAction_8java" ],
    [ "MonsterAvatar.java", "df/d93/MonsterAvatar_8java.html", "df/d93/MonsterAvatar_8java" ],
    [ "MonsterProperty.java", "dd/d9d/MonsterProperty_8java.html", "dd/d9d/MonsterProperty_8java" ],
    [ "NPC.java", "d7/db6/NPC_8java.html", "d7/db6/NPC_8java" ],
    [ "Property.java", "db/d63/Property_8java.html", "db/d63/Property_8java" ],
    [ "PropertyIndex.java", "d4/d0f/PropertyIndex_8java.html", "d4/d0f/PropertyIndex_8java" ],
    [ "SpecialAbility.java", "db/d50/SpecialAbility_8java.html", "db/d50/SpecialAbility_8java" ],
    [ "Spell.java", "de/d9f/Spell_8java.html", "de/d9f/Spell_8java" ],
    [ "SpellAttack.java", "d0/db2/SpellAttack_8java.html", "d0/db2/SpellAttack_8java" ],
    [ "SpellDamages.java", "da/dda/SpellDamages_8java.html", "da/dda/SpellDamages_8java" ],
    [ "SpellRealLevel.java", "d9/d68/SpellRealLevel_8java.html", "d9/d68/SpellRealLevel_8java" ]
];