var namespaceDnD_1_1JavaCsvToJson =
[
    [ "App", "da/df1/classDnD_1_1JavaCsvToJson_1_1App.html", "da/df1/classDnD_1_1JavaCsvToJson_1_1App" ],
    [ "AppTest", "d4/df7/classDnD_1_1JavaCsvToJson_1_1AppTest.html", "d4/df7/classDnD_1_1JavaCsvToJson_1_1AppTest" ],
    [ "AvatarFrame", "dc/d31/classDnD_1_1JavaCsvToJson_1_1AvatarFrame.html", "dc/d31/classDnD_1_1JavaCsvToJson_1_1AvatarFrame" ],
    [ "Digest", "df/d3c/classDnD_1_1JavaCsvToJson_1_1Digest.html", "df/d3c/classDnD_1_1JavaCsvToJson_1_1Digest" ],
    [ "DnDObject", "d0/df2/classDnD_1_1JavaCsvToJson_1_1DnDObject.html", "d0/df2/classDnD_1_1JavaCsvToJson_1_1DnDObject" ],
    [ "EAlignment", "d2/d51/enumDnD_1_1JavaCsvToJson_1_1EAlignment.html", "d2/d51/enumDnD_1_1JavaCsvToJson_1_1EAlignment" ],
    [ "EApplicationStatus", "dd/dd6/enumDnD_1_1JavaCsvToJson_1_1EApplicationStatus.html", "dd/dd6/enumDnD_1_1JavaCsvToJson_1_1EApplicationStatus" ],
    [ "EDices", "d3/d68/enumDnD_1_1JavaCsvToJson_1_1EDices.html", "d3/d68/enumDnD_1_1JavaCsvToJson_1_1EDices" ],
    [ "EMonsterHeader", "da/d98/enumDnD_1_1JavaCsvToJson_1_1EMonsterHeader.html", "da/d98/enumDnD_1_1JavaCsvToJson_1_1EMonsterHeader" ],
    [ "EObjectHeader", "db/db7/enumDnD_1_1JavaCsvToJson_1_1EObjectHeader.html", "db/db7/enumDnD_1_1JavaCsvToJson_1_1EObjectHeader" ],
    [ "ESize", "db/d99/enumDnD_1_1JavaCsvToJson_1_1ESize.html", "db/d99/enumDnD_1_1JavaCsvToJson_1_1ESize" ],
    [ "ESpellAttackType", "d4/dcf/enumDnD_1_1JavaCsvToJson_1_1ESpellAttackType.html", "d4/dcf/enumDnD_1_1JavaCsvToJson_1_1ESpellAttackType" ],
    [ "ESpellDamageType", "df/d7b/enumDnD_1_1JavaCsvToJson_1_1ESpellDamageType.html", null ],
    [ "ESpellHeader", "df/dd7/enumDnD_1_1JavaCsvToJson_1_1ESpellHeader.html", "df/dd7/enumDnD_1_1JavaCsvToJson_1_1ESpellHeader" ],
    [ "ESpellLevel", "df/d4e/enumDnD_1_1JavaCsvToJson_1_1ESpellLevel.html", "df/d4e/enumDnD_1_1JavaCsvToJson_1_1ESpellLevel" ],
    [ "ESpellSchool", "d8/d8d/enumDnD_1_1JavaCsvToJson_1_1ESpellSchool.html", "d8/d8d/enumDnD_1_1JavaCsvToJson_1_1ESpellSchool" ],
    [ "IExportable", "d7/d00/interfaceDnD_1_1JavaCsvToJson_1_1IExportable.html", "d7/d00/interfaceDnD_1_1JavaCsvToJson_1_1IExportable" ],
    [ "IHeader", "db/d49/interfaceDnD_1_1JavaCsvToJson_1_1IHeader.html", "db/d49/interfaceDnD_1_1JavaCsvToJson_1_1IHeader" ],
    [ "JavaCsvToJson", "dc/d31/classDnD_1_1JavaCsvToJson_1_1JavaCsvToJson.html", "dc/d31/classDnD_1_1JavaCsvToJson_1_1JavaCsvToJson" ],
    [ "Monster", "d4/d81/classDnD_1_1JavaCsvToJson_1_1Monster.html", "d4/d81/classDnD_1_1JavaCsvToJson_1_1Monster" ],
    [ "MonsterAction", "dd/dbf/classDnD_1_1JavaCsvToJson_1_1MonsterAction.html", "dd/dbf/classDnD_1_1JavaCsvToJson_1_1MonsterAction" ],
    [ "MonsterAvatar", "d9/d1f/classDnD_1_1JavaCsvToJson_1_1MonsterAvatar.html", "d9/d1f/classDnD_1_1JavaCsvToJson_1_1MonsterAvatar" ],
    [ "MonsterProperty", "de/d58/classDnD_1_1JavaCsvToJson_1_1MonsterProperty.html", "de/d58/classDnD_1_1JavaCsvToJson_1_1MonsterProperty" ],
    [ "NPC", "d8/d2f/classDnD_1_1JavaCsvToJson_1_1NPC.html", "d8/d2f/classDnD_1_1JavaCsvToJson_1_1NPC" ],
    [ "Property", "db/daa/classDnD_1_1JavaCsvToJson_1_1Property.html", "db/daa/classDnD_1_1JavaCsvToJson_1_1Property" ],
    [ "PropertyIndex", "dd/d20/classDnD_1_1JavaCsvToJson_1_1PropertyIndex.html", "dd/d20/classDnD_1_1JavaCsvToJson_1_1PropertyIndex" ],
    [ "SpecialAbility", "db/dba/classDnD_1_1JavaCsvToJson_1_1SpecialAbility.html", "db/dba/classDnD_1_1JavaCsvToJson_1_1SpecialAbility" ],
    [ "Spell", "de/d1f/classDnD_1_1JavaCsvToJson_1_1Spell.html", "de/d1f/classDnD_1_1JavaCsvToJson_1_1Spell" ],
    [ "SpellAttack", "d6/da8/classDnD_1_1JavaCsvToJson_1_1SpellAttack.html", "d6/da8/classDnD_1_1JavaCsvToJson_1_1SpellAttack" ],
    [ "SpellDamages", "da/dab/classDnD_1_1JavaCsvToJson_1_1SpellDamages.html", "da/dab/classDnD_1_1JavaCsvToJson_1_1SpellDamages" ],
    [ "SpellRealLevel", "d9/dcf/enumDnD_1_1JavaCsvToJson_1_1SpellRealLevel.html", null ]
];